config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='movies')),
    path('user/', include('auth_and_login.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

config/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    MovieDetail,
    MovieList,
    ShowAllUsers,
    movie_create,
    movie_delete,
    comments,
    show_movie,
)

app_name = 'movies'
urlpatterns = [
    path('', MovieList.as_view(), name='all_movie'),
    path('movie/<int:pk>/details/', MovieDetail.as_view(), name='detail_movie'),
    path('create_movie/', movie_create, name='create_movie'),
    path('create_movie/<int:m_id>/', movie_create, name='create_movie'),
    path('delete/<int:m_id>/movie/', movie_delete, name='delete_movie'),
    path('comments/<int:m_id>/movie/', comments, name='comments'),

    # Show users data
    path('users/', ShowAllUsers.as_view(), name='users'),

    # Test urls
    path('movie_sorted/', show_movie, name='movie_sorted'),
]

config/core/models.py
# import django needed module's
# Import outside module
from datetime import datetime
from cloudinary import models as cloudinary_models

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Count


class Movie(models.Model):
    """
    Store a movie info
    :Rating
    :title
    :plot
    :year
    :rating:
    :movie runtime
    :movie original url
    :movie image
    """
    NOT_RATED = 0
    RATED_R = 1
    RATED_G = 2
    RATINGS = (
        (NOT_RATED, 'Not Rated'),
        (RATED_R, 'R - Restricted'),
        (RATED_G, 'G - General Audiences')
    )

    title = models.CharField(max_length=100, unique=True)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS
    )
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    image = cloudinary_models.CloudinaryField(
        resource_type='image',
        blank=False
    )
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Title: {self.title}"

    def save(self, *args, **kwargs):
        self.title = self.title.capitalize()
        super(Movie, self).save(*args, **kwargs)


def get_max_comments():
    """Return first 4 movie with more comments"""
    return Movie.objects.all().annotate(post=Count('comments')).order_by('-post')[:4]


class Comments(models.Model):
    """
    Use for comment system, add comment for user to movie
    """
    post = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created_on = models.DateTimeField(default=datetime.now)
    author = models.CharField(max_length=50)

    class Meta:
        """Sorting movie, new is first"""
        ordering = ['created_on']

    def __str__(self):
        return 'Comment for {}'.format(self.post.title)

config/core/forms.py
from django import forms

from .models import Movie, Comments


# Form connect to movie models
class NewMovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        exclude = ('publisher',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),
            'plot': forms.Textarea(attrs={'class': 'form-control'}),
            'year': forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),
            'rating': forms.Select(attrs={'class': 'form-control', 'type': 'select'}),
            'runtime': forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),
            'website': forms.DateInput(attrs={'class': 'form-control', 'type': 'text'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }


# Не се ползва реших че с raw ще е по-добре, не съм решил още!
class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('post', 'body',)

    def __init__(self, *args, **kwargs):
        super(CommentsForm, self).__init__(*args, **kwargs)
        self.fields['post'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['body'].widget.attrs.update(
            {'class': 'form-control'}
        )

config/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView

from .forms import CommentsForm
from .forms import NewMovieForm
from .models import Comments, get_max_comments
from .models import Movie


def show_movie(request):
    """
        Return most comments movies
    """
    movie_with_more_comments = get_max_comments()
    context = {
        'data': movie_with_more_comments
    }

    return render(request, 'core/sort_moview_list.html', context)


class MovieList(ListView):
    """ Return all movies from database """
    template_name = 'core/all_movies.html'
    model = Movie
    context_object_name = 'movies'
    paginate_by = 4


class MovieDetail(DetailView):
    """ Return detail from choice movie """
    template_name = 'core/detail_movie.html'
    model = Movie
    context_object_name = 'movies'


def movie_create(request, m_id=None):
    """
        Use 2 in 1 for create and edit new movie
        for this use and two url's
    """
    if request.user.is_authenticated:
        """
            If user is login get control for create, delete and edit
            else redirect to login page
        """
        context = {}
        movies = None
        if m_id:
            movies = Movie.objects.get(id=m_id)

        form = NewMovieForm(request.POST or None,
                            request.FILES or None, instance=movies)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.publisher = request.user
            movie.save()
            form = NewMovieForm()
            return redirect('movies:all_movie')
        context['form'] = form
        return render(request, 'core/new_movie.html', context)
    return redirect('user_login')


def movie_delete(request, m_id):
    if request.user.is_authenticated:
        context = {}
        movie = get_object_or_404(Movie, id=m_id)
        context['movies'] = movie
        if request.method == 'POST':
            movie.delete()
            return redirect('movies:all_movie')
        return render(request, 'core/delete_movie.html', context)
    return redirect('user_login')


def comments(request, m_id):
    """
    Add comments to movie, show only date and body message
    Logic to view and add new comment is move to tempalte
    """
    # if request.user.is_authenticated:
    context = {}
    movie = get_object_or_404(Movie, id=m_id)
    movie_comments = Comments.objects.filter(post=movie)
    context['movies'] = movie
    context['comments'] = movie_comments
    context['form'] = CommentsForm()
    if request.method == 'GET':
        return render(request, 'core/comments.html', context)
    movie_id = request.POST['movie_id']
    movie_body = request.POST['movie_body']
    Comments.objects.create(post=Movie.objects.get(id=movie_id), body=movie_body, author=request.user)
    return redirect('movies:comments', m_id)
    # return redirect('movies:user_login')


class ShowAllUsers(LoginRequiredMixin, ListView):
    template_name = 'core/show_all_users.html'
    context_object_name = 'persons'
    model = User

config/templates/core/all_movies.html
{% extends 'base.html' %}
{% block title %}All - Movies {% endblock title %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock css %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}


    <div class="movie_list_view">
        {% for movie in movies %}
            <div class="card m_box">
                <img class="card-img-top" src="{{ movie.image.url }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.title }}</h5>
                    <p class="card-text">{{ movie.plot|truncatewords:5 }}</p>
                    <a href="{% url 'movies:detail_movie' movie.pk %}" class="btn btn-primary">Детаили</a>
                </div>
            </div>
        {% empty %}
            Все още няма заглавия
        {% endfor %}

    </div>
    <br/>
    <nav aria-label="Page navigation example">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&laquo;</a>
                    </li>
                {% endif %}
                {% for i in paginator.page_range %} {% if page_obj.number == i %}
                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link"
                        >&raquo;</a
                        >
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </nav>

    <script>
        $(".alert-success").fadeOut(3500);
    </script>

{% endblock content %}

config/templates/core/comments.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock title %}
{% load static %}
{% block content %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock css %}

    <div>
        <h1>Коментари на потребители</h1>
        <div class="main_span">
            <h2 class="h2_title">{{ movies.title }}</h2>
        </div>

        {% if comments %}
            {% for comment in comments %}
                <p>Дата: {{ comment.created_on|date:"d M Y H:m" }} - {{ comment.body }}</p>Автор: {{ comment.author }}
                <a href="{% url 'profile_info' comment.author %}">Info</a>
                <hr>
            {% endfor %}
        {% else %}
            <p>Няма коментари. Може да добавите първи.</p>
        {% endif %}


        {% if user.is_authenticated %}
            <form action="{% url 'movies:comments' movies.id %}" method="POST">
                {% csrf_token %}
                <label for="movie_name">Име
                    <input type="text" value="{{ movies.title }}" class="form-control input-lg" id="movie_name" disabled
                           name="movie_name">
                </label>
                <br>
                <label for="movie_text_area">Контент
                    <textarea rows="4" cols="100" id="movie_text_area" class="form-control"
                              name="movie_body"></textarea>
                </label>
                <input type="hidden" value="{{ movies.id }}" name="movie_id">
                <input type="submit" value="Запази" class="btn btn-primary form-control">
            </form>
        {% else %}
            <a href="{% url 'user_login' %}" class="my-0"><h5 class="my-0">Трябва да сте логнати за да добавите
                коментар</h5>
            </a>
        {% endif %}

    </div>


{% endblock content %}

config/templates/core/delete_movie.html
{% extends 'base.html' %}
{% block title %}Delete - Moview {% endblock title %}
{% block content %} 

<form action="{% url 'movies:delete_movie' movies.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Потвърди изтриването" />
</form>


{% endblock content %}

config/templates/core/detail_movie.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock title %}
{% load static %}
{% block content %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock css %}

    <div>
        <div class="main_span">
            <h2 class="h2_title">{{ movies.title }}</h2> <span
                class="my_right">Rated: {{ movies.get_rating_display }}</span>
        </div>
        <p>Година: {{ movies.year }} - {{ movies.runtime }} минути</p>
        <p>{{ movies.plot }}</p>
        <a href="{{ movies.website }}" target="_blank">Към адреса...</a> ||

        <a href="{% url 'movies:comments' movies.id %}" target="_blank">Коментари</a>

        <hr>
        <div class="edit_delete">
            {% if user.is_authenticated and user.id == movies.publisher.id or request.user.is_superuser %}
                <ul>
                    <li><a href="{% url 'movies:create_movie' movies.id %} " class="btn btn-success">Редакция</a></li>
                    <li><a href="{% url 'movies:delete_movie' movies.id %}" class="btn btn-danger">Изтрии</a></li>
                </ul>
            {% endif %}
        </div>
    </div>


{% endblock content %}

config/templates/core/edit_delete.html
{% if user.is_authenticated %}
<ul>
    <li><a href="{% url 'movies:create_movie' movies.id %}">Редакция</a></li>
    <li><a href="{% url 'movies:delete_movie' movies.id %}">Изтрии</a></li>
</ul>
{% endif %}

config/templates/core/edit_moview.html
{% extends 'base.html' %}
{% block title %}Edit - Movie {% endblock title %}
{% block content %} 

{% endblock content %}

config/templates/core/new_movie.html
{% extends 'base.html' %}
{% block title %}New - Movie {% endblock title %}
{% block content %} 

<h5>Добави / Редактираи заглавие</h5>
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
<input type="submit" value="Запази" class="form-control btn btn-secondary">
</form>

{% endblock content %}

config/templates/core/right_menu.html
{% load all_movies %}

<div class="col-md-4 order-md-2 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-4">
        <span class="text-muted">Навигация</span>
        <span class="badge badge-secondary badge-pill">Тотал movie {% movies_count %}</span>
    </h4>
    <ul class="list-group mb-3 sticky-top">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <a href="{% url 'movies:all_movie' %}">
                <div>
                    <h6 class="my-0">Всички филми</h6>
                    <small class="text-muted">Списък със заглавията</small>
                </div>
            </a>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <a href="{% url 'movies:create_movie' %}">
                <div>
                    <h6 class="my-0">Добави нов филм</h6>
                    <small class="text-muted">Добавете ново заглавие</small>
                </div>
            </a>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <a href="{% url 'movies:movie_sorted' %}">
                <div>
                    <h6 class="my-0">Most comment Movie</h6>
                    <small class="text-muted">Показва първите 4 най-коментирани филма</small>
                </div>
            </a>
        </li>
        {% if request.user.is_superuser %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <a href="{% url 'movies:users' %}">
                    <div>
                        <h6 class="my-0">Show all profile's</h6>
                        <small class="text-muted">Показва профилите на потребителите</small>
                    </div>
                </a>
            </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            {% if user.is_authenticated %}
                <a href="{% url 'edit' %}">
                    <div>
                        <h6 class="my-0">Edit Profile</h6>
                    </div>
                </a>
                <a href="{% url 'logout' %}?next=/">
                    <div>
                        <h6 class="my-0">Logout {{ user }}</h6>
                    </div>
                </a>
            {% else %}
                <a href="{% url 'user_login' %}">
                    <div>
                        <h6 class="my-0">Login</h6>
                        <small class="text-muted">контролен панел</small>
                    </div>
                </a>
            {% endif %}
        </li>
    </ul>
</div>

config/templates/core/show_all_users.html
{% extends 'base.html' %}
{% block title %}Edit - Movie {% endblock title %}
{% block content %}
    {% if persons %}
        <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Потребителско име</th>
                <th>Първо име</th>
                <th>Последно влизане</th>
                <th>Емеил</th>
            </tr>
        </thead>
        {% for user in persons %}
            <tr>
                <td><a href="{% url 'profile_info' user.username %}">{{ user.username }}</a></td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_login|date:'d/m/Y H:i' }}</td>
                <td>{{ user.email }}</td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock content %}

config/templates/core/sort_moview_list.html
{% extends 'base.html' %}
{% block title %}Sorted - Moview {% endblock title %}
{% block content %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Име</th>
            <th>Година</th>
            <th>Коментари</th>
            <th>Към коментарите</th>
        </tr>
        </thead>
        {% for d in data %}
            <tr>
                <td>{{ d.title }}</td>
                <td>{{ d.get_rating_display }}</td>
                <td>{{ d.comments.count }}</td>
                <td><a href="{% url 'movies:comments' d.id %}">Info</a></td>
            </tr>

        {% endfor %}
    </table>
{% endblock content %}